#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

NAME=$1
shift 1

m4 -D_NAME=$NAME "$@" "${BASH_SOURCE%/*}/body.m4" > body.tmp
exit_if_nzero $?

RESPONSE=$(curl ${CURL_OPTS[@]} -d @body.tmp -X PATCH "${DHOST}/odata/v2/DataStores('$NAME')")
format_response "$RESPONSE"

rm body.tmp
