#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

ID=$1
shift 1

m4 -D_ID=$ID "$@" "${BASH_SOURCE%/*}/body.m4" > body.tmp
exit_if_nzero $?

RESPONSE=$(curl ${CURL_OPTS[@]} -d @body.tmp -X PATCH "http://${DHOST}/odata/v2/DataStores('$ID')")
format_response "$RESPONSE"

rm body.tmp
