#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

ID=$1

m4 -D_URI="${DHOST}/odata/v1/Collections('$2')" "${BASH_SOURCE%/*}/../m4/odata2link.m4" > body.tmp
exit_if_nzero $?

RESPONSE=$(curl ${CURL_OPTS_XML[@]} -d @body.tmp "${DHOST}/odata/v1/Scanners(${ID})/\$links/Collections")
format_response "$RESPONSE"

rm body.tmp
