#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

USERNAME=$1

m4 -D_URI="http://${DHOST}/odata/v1/Products('$2')" "${BASH_SOURCE%/*}/body.m4" > body.tmp
exit_if_nzero $?

RESPONSE=$(curl ${CURL_OPTS_XML[@]} -d @body.tmp "http://${DHOST}/odata/v1/Users('${USERNAME}')/\$links/Cart")
format_response "$RESPONSE"

rm body.tmp
