#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

USERNAME=$1

RESPONSE=$(curl ${CURL_OPTS_XML[@]} "${DHOST}/odata/v1/Users('${USERNAME}')/\$links/Cart")
format_response "$RESPONSE"
