#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

RESPONSE=$(curl ${CURL_OPTS_XML[@]} -X POST "${DHOST}/odata/v2/Scanners($1)/OData.DHuS.StopScanner")
format_response "$RESPONSE"
