#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic
check_command md5sum
check_xmllint_xpath

FILEPATH=$1
shift 1

md5=`md5sum "$FILEPATH" | cut -d ' ' -f 1`
filename=`basename "$FILEPATH"`

curl -X POST --basic -u ${DLOGIN}:${DPASS} --data-binary @${FILEPATH} \
  --header "Content-Type:application/octet-stream" \
  --header "Accept:application/atom+xml" \
  --header "Prefer:return-content" \
  -o out.xml \
  "${DHOST}/odata/v1/Ingests"
exit_if_nzero $?
if [ ! -s out.xml ]; then exit 1; fi

id=`xmllint --nsclean --xpath "//*[name()='d:Id']/text()" out.xml`
remote_md5=`xmllint --nsclean --xpath "//*[name()='d:MD5']/text()" out.xml | tr [:upper:] [:lower:]`
rm out.xml

if [ "$md5" != "$remote_md5" ] ; then
  echo "MD5 are different: local($md5) != remote($remote_md5), deleting uploaded product."
  echo 'Please retry.'
  echo -n 'Removing uploaded data ... '
  RESPONSE=$(curl ${CURL_OPTS_XML[@]} -X DELETE "${DHOST}/odata/v1/Ingests($id)")
  format_response "$RESPONSE"
else
  m4 -D_FILENAME=$filename "$@" "${BASH_SOURCE%/*}/body.m4" > body.tmp
  exit_if_nzero $?

  RESPONSE=$(curl ${CURL_OPTS[@]} -X PUT -d @body.tmp "${DHOST}/odata/v1/Ingests($id)")
  format_response "$RESPONSE"

  rm body.tmp
fi
