#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

if [ $# -eq 1 ]; then
  key="('$1')"
fi

RESPONSE=$(curl ${CURL_OPTS[@]} "http://${DHOST}/odata/v2/Evictions$key")
format_response "$RESPONSE"
