#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

NAME="'$1'"
shift 1

m4 "$@" "${BASH_SOURCE%/*}/body.m4" > body.tmp
exit_if_nzero $?

RESPONSE=$(curl ${CURL_OPTS[@]} -X PATCH -d @body.tmp "${DHOST}/odata/v2/Evictions($NAME)")
format_response "$RESPONSE"

rm body.tmp
