#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

arg=$(make_key_string "$1")

RESPONSE=$(curl -X DELETE ${CURL_OPTS_XML[@]} "${DHOST}/odata/v2/Products${arg}")
format_response "$RESPONSE"
