#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

arg=$(make_key_string "$1")$(make_uri_params "$2")

RESPONSE=$(curl -Ss --basic -u ${DLOGIN}:${DPASS} -OJ "${DHOST}/odata/v2/Products${arg}/\$value")
format_response "$RESPONSE"
