#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

key=$(make_key_string "$1")

RESPONSE=$(curl -Ss --basic -u ${DLOGIN}:${DPASS} -I "${DHOST}/odata/v2/Products${key}/\$value")
echo "$RESPONSE"
