#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

#PARAMS="<parameters><Reason>$2</Reason></parameters>"
PARAMS="{\"Reason\": \"${2}\" }"

RESPONSE=$(curl ${CURL_OPTS_JSON[@]} -X POST -d "$PARAMS" "${DHOST}/odata/v2/Users('$1')/OData.DHuS.Lock")
echo "$RESPONSE"
