#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

sync_type="$1"
shift 1

m4 -D_SYNC_TYPE="$sync_type" "$@" "${BASH_SOURCE%/*}/body.m4" > body.tmp
exit_if_nzero $?

RESPONSE=$(curl ${CURL_OPTS[@]} -d @body.tmp ${DHOST}/odata/v2/Synchronizers)
format_response "$RESPONSE"

rm body.tmp
