#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

sync_type="$1"
key="$2"
shift 2

m4 -D_SYNC_TYPE="$sync_type" "$@" "${BASH_SOURCE%/*}/body.m4" > body.tmp
exit_if_nzero $?

RESPONSE=$(curl ${CURL_OPTS[@]} -X PATCH -d @body.tmp "http://${DHOST}/odata/v2/Synchronizers($key)")
format_response "$RESPONSE"

rm body.tmp
