#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

m4 -D_ID="0L" "$@" "${BASH_SOURCE%/*}/body.m4" > body.tmp
exit_if_nzero $?

RESPONSE=$(curl ${CURL_OPTS[@]} -d @body.tmp ${DHOST}/odata/v1/Synchronizers)
format_response "$RESPONSE"

rm body.tmp
