#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

ID=$1
shift 1

m4 -D_ID=$ID "$@" "${BASH_SOURCE%/*}/body.m4" > body.tmp

RESPONSE=$(curl -X PUT ${CURL_OPTS[@]} -d @body.tmp "${DHOST}/odata/v1/Synchronizers($ID)")
format_response "$RESPONSE"

rm body.tmp
