#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

RESPONSE=$(curl ${CURL_OPTS_XML[@]} -X POST "http://${DHOST}/odata/v1/LockUser?username='$1'&reason='$2'")
format_response "$RESPONSE"
