#!/bin/bash

source "${BASH_SOURCE%/*}/../functions.sh.inc"
check_basic

RESPONSE=$(curl ${CURL_OPTS_XML[@]} -X POST "http://${DHOST}/odata/v1/UnlockUser?username='$1'&restriction='$2'")
format_response "$RESPONSE"
